### PR TITLE
Feature/local file system bootstrap params

### PR DESCRIPTION
**Pull request by jcord04**
Relates to issue raised - https://github.com/creocoder/yii2-flysystem/issues/58

### CODE REVIEW

**Comment by schmunk42** [comment]
@jcord04 
Is this fully backward-compatible, especially the part with `$permissons`?

CC: @handcode @eluhr


---

[update] for reference: https://github.com/thephpleague/flysystem/blob/1.x/src/Adapter/Local.php

**Comment by jcord04** [comment]
Hi @schmunk42 ,

I believe it is, the `__constructor` in `League\Flysystem\Adapter\Local` has defaulted arguments ` public function __construct($root, $writeFlags = LOCK_EX, $linkHandling = self::DISALLOW_LINKS, array $permissions = [])` which I've mimicked in `src/LocalFilesystem.php` 

Regarding the `$permissions`, this is passing the default (empty array) to the Local constructor. Looking into the constructor itself, its doing an `array_replace_recursive` and favouring the `static::$permissions` value unless either 
`file` or `dir` is passed in the `$permissions` argument.

I've tried to make sure that `src/LocalFilesystem.php` is initialising `League\Flysystem\Adapter\Local` without changing its default behaviour, while giving the option in Yii2 to change these defaults should it be required.
 
Happy to change the approach if it can be improved 👍

**Comment by jcord04** [comment]
Hi @schmunk42, 

Is there anything I can do to help get this merged?

Thanks

Jez

**Comment by jcord04** [comment]
Hi @schmunk42 ,

Sorry to chase this, but just wanted to see if this might get merged in :) I'd love to keep the original library and not run a fork 👍 

Thanks

**Comment by schmunk42** [comment]
Hi,Sorry I am in holiday and will try to merge tonight or tomorrow.Von meinem iPhone gesendetAm 28.07.2023 um 17:27 schrieb Jez Cordonnier ***@***.***>:﻿
Hi @schmunk42 ,
Sorry to chase this, but just wanted to see if this might get merged in :) I'd love to keep the original library and not run a fork 👍
Thanks

**Comment by schmunk42** [comment]
Done & available in 1.2.0, sorry for the delay.

**Comment by jcord04** [comment]
Thanks @schmunk42 this is awesome!

**Pull request merged**
