### PR TITLE
added Google Cloud Filesystem

### PR DESCRIPTION
**Pull request by schmunk42**

### CODE REVIEW

**Comment by gusev-genotek** [comment]
Kindly asking to merge this feature into master. Exactly what I need right now.

**Comment by razvanphp** [comment]
Automatic authentication in google app engine does not work because of `throw new InvalidConfigException` in init(): [documentation](https://github.com/Superbalist/flysystem-google-cloud-storage).

>  * If running in Google App Engine, the built-in service account associated with the application will be used.
>  * If running in Google Compute Engine, the built-in service account associated with the virtual machine instance will be used.

**Comment by schmunk42** [comment]
@razvanphp Sorry, I do not understand the problem you are referring to. 

We are using this since a while without any issues. 

Can you describe more in detail or create a new issue if needed.

**Comment by razvanphp** [comment]
In [here](https://github.com/googleapis/google-cloud-php-core/blob/master/src/ClientTrait.php#L120), if we specify keyFilePath, then automatic authentication from ENV for example or Google App Engine will not work anymore, because file is the first one in priority. I would suggest to create `$this->config` and pass this to the Client like this:

```
    protected function prepareAdapter()
    {
        if (isset($this->config['keyFilePath'])) {
            $this->config['keyFilePath'] = \Yii::getAlias($this->config['keyFilePath']);
        }

        $client = new StorageClient($this->config);
        $bucket = $client->bucket($this->bucket);
        return  new GoogleStorageAdapter($client, $bucket);
    }
```

**Comment by schmunk42** [comment]
How do handle `projectId`?

**Comment by razvanphp** [comment]
In Google App Engine it is also not required, it's automatically injected from the ENV.

**Comment by schmunk42** [comment]
Can you create a PR, which is backward-compatible?

**Pull request merged**
